import { StyleSheet } from "react-native"
import colors from "../../../utils/colors"

export default StyleSheet.create({
    container:{
        flex:1,
        backgroundColor:colors.bgcolor
    },
    tpview:{
        flexDirection:"row",
        flex:0.15,
        backgroundColor:colors.view_bl,
        borderBottomLeftRadius:20,
        borderBottomRightRadius:20,
    },
    menu:{
        height:35,
        width:35,
        marginHorizontal:20,
        tintColor:colors.bgcolor
    },
    searchinp:{
        backgroundColor:colors.bgcolor2,
        color:colors.inactive,
        height:40,
        borderRadius:10
    },
    outview:{
        flex:0.85,
        padding:20,
        overflow:"scroll",
        marginBottom:"15%"
    },
    flelement:{
        height:90,
        flexDirection:"row",
        backgroundColor:colors.bgcolor2,
        borderRadius:20,
        borderWidth:2,
        borderColor:colors.view_bl,
        marginVertical:20,
        overflow:"hidden"
    },
    flimagecontainer:{
        flex:0.3,
        backgroundColor:colors.view_bl,borderRadius:18,
        borderBottomRightRadius:100,
        borderTopRightRadius:0,
    },
    fltext:{
        fontSize:20,
        fontWeight:"bold",
        color:colors.txtin
    },
    flsmlltext:{
        fontSize:15,
        color:colors.inactive
    },
    empty:{
        display:"none"
    },
    free:{
        left:"75%",
        bottom:"55%",
        height:"25%",
        width:"35%",
        transform:[{rotate:"45deg"}],
        backgroundColor:'green',position:'absolute'
    },
    paid:{
        left:"75%",
        bottom:"55%",
        height:"25%",
        width:"35%",
        transform:[{rotate:"45deg"}],
        backgroundColor:'red',position:'absolute'  
    }
})